version: '3.8'

services:
  app:
    build: .
    ports:
      - "8032:4000"
    environment:
      - APP_ENV=prod
    env_file:
      - .env
    depends_on:
      datomic:
        condition: service_healthy
    restart: unless-stopped
    command: sh -c "sleep 5 && java -jar app.jar"  # додано затримку, як fallback

  datomic:
    build:
      context: ./datomic-pro
    ports:
      - "8998:8998"     # web-admin
      - "8999:8999"     # додано: порт для peer/datomic підключення
    volumes:
      - datomic_data:/opt/datomic/datomic-pro-1.0.7364/data
      - ./datomic-pro/transactor.properties:/opt/datomic/datomic-pro-1.0.7364/config/transactor.properties
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8999"]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  datomic_data:
