name: Migrate Prod DB

on:
  workflow_dispatch:

jobs:
  migrate-prod:
    name: Run DB migrations on prod
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run migrations on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            IMAGE_NAME="ghcr.io/${{ github.repository }}:migrate-${{ github.sha }}"
            CONTAINER_NAME="marketplace-shum-app"

            echo "--- Pulling new migrate image: $IMAGE_NAME ---"
            docker pull $IMAGE_NAME

            echo "--- Stopping and removing app container before migrations (if running) ---"
            if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
                docker stop $CONTAINER_NAME
                docker rm -f $CONTAINER_NAME || true
            fi

            echo "--- Running migrations ---"
            docker run --env-file=.env --rm \
              $IMAGE_NAME 